[features]
seeds = false
skip-lint = false
[programs.localnet]
sporting_labs_stake_pool = "41MZASop6YTB5UmYNSDFxFJ4QYEMeDY9f7WcABLUmfoB"
raindrops_item = "itemX1XWs9dK8T2Zca4vEEPfCAhRc7yvYFntPjTTVx6"
raindrops_player = "p1ay5K7mcAZUkzR1ArMLCCQ6C58ULUt7SUi7puGEWc1"

[programs.devnet]
sporting_labs_stake_pool = "41MZASop6YTB5UmYNSDFxFJ4QYEMeDY9f7WcABLUmfoB"
raindrops_item = "itemX1XWs9dK8T2Zca4vEEPfCAhRc7yvYFntPjTTVx6"
raindrops_player = "p1ay5K7mcAZUkzR1ArMLCCQ6C58ULUt7SUi7puGEWc1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kulture/.config/solana/sporting-labs-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
